<a href="https://colab.research.google.com/github/itcxx/Notebook/blob/main/pytorchBasicOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pytorch基础操作



1. Tensor创建

* 标量

In [44]:
import torch

In [45]:
torch.tensor(2)

tensor(2)

In [46]:
torch.tensor([1.1])

tensor([1.1000])

In [47]:

torch.FloatTensor(2)  #输入的是维度

tensor([2.8247e-36, 0.0000e+00], dtype=torch.float32)

In [48]:
torch.FloatTensor(2,2)

tensor([[2.8248e-36, 0.0000e+00],
        [3.9236e-44, 0.0000e+00]], dtype=torch.float32)

In [49]:
#shape 是属性， size()是函数
a=torch.FloatTensor(3,4)
print("a.shape: ",a.shape)
print("a.shape[0]: ",a.shape[0])  #返回dim=0的大小，即0维度0的大小

print("a.size(): ",a.size())
print("a.size(0): ",a.size(0))

a.shape:  torch.Size([3, 4])
a.shape[0]:  3
a.size():  torch.Size([3, 4])
a.size(0):  3


In [50]:
# numel()返回tensor的大小
# dim() 返回维度的大小

a=torch.rand(2,2,3)
print(a)
print("a.numel(): ",a.numel())
print("a.dim(): ",a.dim())

tensor([[[0.1097, 0.4582, 0.0096],
         [0.1070, 0.3879, 0.0994]],

        [[0.7694, 0.3392, 0.6389],
         [0.5136, 0.3745, 0.0887]]])
a.numel():  12
a.dim():  3


In [51]:
#创建全为1的数组
import numpy as np
torch.ones(2,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [52]:
#from_numpy() 将numpy数据转换成tensor数据
a=np.array([2,3,3])
torch.from_numpy(a)

tensor([2, 3, 3])

> 注意：小写tensor只能接收数据类型,不能接收维度信息,大学Tensor()可以接收数据信息和维度信息

In [53]:
torch.Tensor(2,3)

tensor([[3.6793e-316, 8.3216e-317, 2.1220e-314],
        [2.2941e+199,  1.2882e-57,  6.9879e+98]])

In [54]:
torch.Tensor([2,3])

tensor([2., 3.])

In [55]:
torch.tensor([2,3])

tensor([2, 3])

In [56]:
torch.tensor(2,3)

TypeError: ignored

> arange() 生成等差数列
> linspace() 等分数据
> ones(),zeros(),eye()
>full()

In [71]:
# torch.arange()  //生成等差数列
# torch.full()  //生成相同数值的数列

In [75]:
torch.arange(1,10,1)  #1到10,差值为1


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
torch.arange(1,10,2)  #插值为2

tensor([1, 3, 5, 7, 9])

In [77]:
torch.full((2,3),9)

tensor([[9, 9, 9],
        [9, 9, 9]])

In [79]:
torch.linspace(1,10,5)  #生成1，到10之间的5个间隔相等的数

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [80]:
torch.eye(3,3)  #生成单位矩阵

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### 生成为初始化的数据

In [57]:
# 创建为初始化的数据，
torch.empty(2,3)

tensor([[3.6794e-316, 1.1858e-322, 2.1220e-314],
        [4.7647e+233, 4.6100e+228, 1.6777e+243]])

In [58]:
# tensor()函数的默认类型为FloatTensor
torch.tensor([1.2,3]).type()

'torch.DoubleTensor'

In [59]:
# 设置默认生成类型 set_default_tensor_type()
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2,3]).type()

'torch.DoubleTensor'

### 随机初始化

In [60]:
# torch.rand()  //采用的0~1的均匀随机抽样

torch.rand(3,3) #生成[0,1)之间的3x3矩阵


tensor([[0.1528, 0.8729, 0.2363],
        [0.1066, 0.6708, 0.9374],
        [0.3908, 0.0228, 0.9010]])

In [62]:
# torch.rand_like(a)  //生成和a的shape相同的0~1随机样本
a=torch.rand(3,3)
b=torch.rand_like(a)
b

tensor([[0.4969, 0.6390, 0.2799],
        [0.7217, 0.8040, 0.2005],
        [0.5400, 0.0307, 0.9585]])

In [81]:
# torch.randint(min,max,[shape])  #[min,max)
torch.randint(1,10,[2,3])

tensor([[6, 5, 4],
        [7, 8, 5]])

In [83]:
torch.randperm(11) #生成0到10的数，无序

tensor([ 4,  5,  3,  9,  8, 10,  1,  6,  7,  0,  2])

### 生成正态分布的数据

> torch.randn() //正太分布（0，1） 均值为0，方差为1

In [64]:
torch.randn(2,2)


tensor([[-0.0202,  0.0177],
        [-0.0702,  1.2394]])

### 生成随机正态分布

In [65]:
# torch.normal(mean=x,std=xx)  //mean: 均值， std为方差


In [66]:
torch.full((2,3),2)

tensor([[2, 2, 2],
        [2, 2, 2]])

In [70]:
# 输出1x10的一维度tensor,均值是10x[0] ,方差是[1,0.9,0.8,...]
torch.normal(mean=torch.full([10],0.),std=torch.arange(1,0,-0.1))

tensor([ 1.2162,  0.8851, -0.7124,  0.1778, -0.6152, -0.8955,  0.0363, -0.1423,
         0.0973, -0.0658])

### 索引与切片

In [89]:
# 生成28x28的三通道4张图片 

a=torch.rand(4,3,28,28)

print("a[0].shape: ",a[0].shape)
print("a[0,0].shpae：",a[0,0].shape)
print("a[0,0,0].shape: ",a[0,0,0].shape)


a[0].shape:  torch.Size([3, 28, 28])
a[0,0].shpae： torch.Size([28, 28])
a[0,0,0].shape:  torch.Size([28])


* a.shape -> torch.size(4,3,28,28)
* a[:2].shape   //表示前两张照片
* a[:2,:1,:,:]   //表示前两张图片的第0个通道的所有数据
* a[:2,1:,:,:]   //表示前两张图片中从第一通道到最末尾通道的所有数据
* a[:2,-1:,:,:]  //表示前两张图片中最后一个通道的所有数据
#### [0:28:2] //表示从[0,28)的每隔2个数采样一次



In [92]:
a.shape

torch.Size([4, 3, 28, 28])

In [91]:
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

> torch.index_select()

    torch.index_select(input,dim,index,out=None)->Tensor

沿着指定维度对输入进行切片，取index中指定的相应项（index为一个LongeTensor),然后返回一个新的张量，返回的张量与原始张量 Tensor 在指定的轴上有相同的维度

注意： 返回的张量不与原始张量共享内存空间

参数：
* input(Tensor) - 输入张量
* dim(int) - 索引的轴
* index(LongTensor) - 包含索引下标的一维张量
* out - 目标张量


In [99]:
x=torch.randn(3,4)
print("x=: ")
print(x)
indices=torch.LongTensor([0,2])
print("index_select(x,0,[0,2]):")
torch.index_select(x,0,indices)

print("index_select(x,1,[0,2]):")
torch.index_select(x,1,indices)

x=: 
tensor([[-1.4129,  1.3549, -0.5821,  0.7717],
        [-1.8078, -0.8244,  1.2352, -1.1828],
        [ 0.3480, -1.2380, -0.6145,  0.8827]])
index_select(x,0,[0,2]):
index_select(x,1,[0,2]):


tensor([[-1.4129, -0.5821],
        [-1.8078,  1.2352],
        [ 0.3480, -0.6145]])

### 维度变换

* view()
* reshape()
* suqeeze()   降低维度
* unsqueeze()  增加维度，不增加数据
* expand()
* repeat()


In [102]:
# view()和reshape()是通用的，让reshape()候来的版本添加的

a=torch.rand(4,1,28,28)
print("a.shape:")
print(a.shape)
print("a.view: 操作")
print(a.view(4,28*28).shape)
print(a.view(4*28,28).shape)

a.shape:
torch.Size([4, 1, 28, 28])
a.view: 操作
torch.Size([4, 784])
torch.Size([112, 28])


In [106]:
# unsqueeze只增加数据的维度不改变数值

a=torch.tensor([1.2,2.3])
print(a.shape)
print(a.unsqueeze(-1))  #在最后一个位置增加一个维度
print(a.unsqueeze(-1).shape)

torch.Size([2])
tensor([[1.2000],
        [2.3000]])
torch.Size([2, 1])


In [112]:
b=torch.rand(32)
print("b.shape: ",b.shape)
print("b.unsqueeze(0): ",b.unsqueeze(0).shape)
print("b.unsqueeze(1).unsqueeze(2).unsqueeze(0):",b.unsqueeze(1).unsqueeze(2).unsqueeze(0).shape)
# 上行中unsqueeze的顺序不同结果不一样


b.shape:  torch.Size([32])
b.unsqueeze(0):  torch.Size([1, 32])
b.unsqueeze(1).unsqueeze(2).unsqueeze(0): torch.Size([1, 32, 1, 1])


In [118]:
# squeeze() 删除所有的维度中数值为1的维度
b=torch.rand(1,32,1,1)
print("b.shape:",b.shape)
print("b.squeeze().shape: ",b.squeeze().shape)  
print("b.squeeze(0).shape",b.squeeze(0).shape)
print("b.squeeze(1).shape",b.squeeze(1).shape) #因为dim=1维度是32所以不做操作
print("b.squeeze(-1).shape",b.squeeze(-1).shape)

b.shape: torch.Size([1, 32, 1, 1])
b.squeeze().shape:  torch.Size([32])
b.squeeze(0).shape torch.Size([32, 1, 1])
b.squeeze(1).shape torch.Size([1, 32, 1, 1])
b.squeeze(-1).shape torch.Size([1, 32, 1])


squeeze()   //删除dim=1的所有维度b=torch.randn(1,32,1,1)

b.squeeze().shape -> torch.size([32])

b.squeeze(0).shape  ->torch.size([32,1,1])

b.squeeze(-1).shape  ->torch.size([1,32,1])

### 维度扩展操作

    # expand 不会主动复制数据，节约内存
    # repead 会复制数据

* expand操作要求，只能在相同的维度上进行扩展，并且只能从1到多


    [1,32,1,1] -> [4,32,14,14] 

In [124]:
# expand 不会主动复制数据，节约内存，在相同的维度上进行扩展


a=torch.rand(4,32,14,14)

b=torch.rand(1,32,1,1)
print(b.shape)

b.expand(4,32,14,14).shape

b.expand(-1,32,-1,-1).shape  # -1表示保存相同的维度不变




torch.Size([1, 32, 1, 1])


torch.Size([1, 32, 1, 1])

In [133]:
a=torch.rand(1,2)
print(a)

print("a.expand(4,2):")
print(a.expand(4,2))

tensor([[0.8133, 0.3522]])
a.expand(4,4):
tensor([[0.8133, 0.3522],
        [0.8133, 0.3522],
        [0.8133, 0.3522],
        [0.8133, 0.3522]])


In [139]:
# repeat(): 中的参数表示在每个维度上的重复次数

b=torch.rand(1,32,1,1)

print("b shape:",b.shape)

print("b.repeat(4,32,1,1): ",b.repeat(1,32,1,1).shape)
print("b.repeat(4,1,1,1): ",b.repeat(4,1,1,1).shape)

b shape: torch.Size([1, 32, 1, 1])
b.repeat(4,32,1,1):  torch.Size([1, 1024, 1, 1])
b.repeat(4,1,1,1):  torch.Size([4, 32, 1, 1])


In [142]:
a=torch.rand(2,2)
print(a)

print(a.repeat(1,2))
print(a.repeat(2,1))

tensor([[0.4803, 0.2012],
        [0.4196, 0.7614]])
tensor([[0.4803, 0.2012, 0.4803, 0.2012],
        [0.4196, 0.7614, 0.4196, 0.7614]])
tensor([[0.4803, 0.2012],
        [0.4196, 0.7614],
        [0.4803, 0.2012],
        [0.4196, 0.7614]])


### 位置转换 T， transpose（）

transpose() 进行维度转换

transpose()之后数据是不连续的，所以要用.contiguous() 函数让它连续

transpose(1,2) , //表示将第一维和第2维进行交换

In [145]:
a=torch.rand(1,2,5,5)
print(a.shape)

print(a.transpose(1,2).shape) #将第一维和第二维进行交换

torch.Size([1, 2, 5, 5])
torch.Size([1, 5, 2, 5])


In [146]:
a=torch.rand(2,3)
print("a:")
print(a)

print("a.transpose(0,1):")
print(a.transpose(0,1))

a:
tensor([[0.5398, 0.1968, 0.9092],
        [0.0160, 0.4829, 0.5665]])
a.transpose(0,1):
tensor([[0.5398, 0.0160],
        [0.1968, 0.4829],
        [0.9092, 0.5665]])


### 熵(entropy)，交叉熵(cross entropy)，和KL散度（Kullback-Leibler divergence,relative entropy)

In [152]:
#计算a的熵 H(a)=-sum（Pi*ln(Pi))
a=torch.Tensor([0.2,0.2,0.2,0.2,0.2])
entropy=-(torch.log2(a)).sum()
print(entropy)

tensor(11.6096)


In [151]:
#计算a,b的KL散度（KL divergence) 
# KL(p,q) ,用来衡量概率分布p,和q的区别有多大，当KL(p,q)=0时表示p=q
# KL(p,q)=H(p,q)-H(p) 等于交叉熵pq-熵p
# KL(p,q)=sum(pi*ln(pi/qi))


tensor([-2.3219, -2.3219, -2.3219, -2.3219])

In [153]:
p=torch.Tensor([0.1,0.1,0.1,0.7])
q=torch.Tensor([0.1,0.1,0.1,0.7])

#计算KL(p,q)散度的值，因为p=q，所以值为0

KL=(p*torch.log2(p/q)).sum()
print(KL)


tensor(0.)


In [ ]:
# 交叉熵H(p,q)=-sum(pi*ln(qi))
# 在KL 散度中KL(p,q)=H(p,q)-H(p) 如果H(p)是固定的(验证label是固定的)则
# 计算KL散度=0时，就等价于起H(p,q)交叉熵的最小值
